# **Using NumPy**

Once you've installed NumPy you can import it as a library:

In [ ]:
import numpy as np

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. Let's start by discussing arrays.

# Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [ ]:
a = [1,2,3,4,5]
arr = np.array(a)
arr

array([1, 2, 3, 4, 5])

Lets create a matrix using list

In [ ]:
a = [[1,2,3],[4,5,6],[7,8,9]]
arr = np.array(a)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Now lets see how matlix looks like using numpy arrays

## Built-in Methods

there are lots of build in methods to create an array lets create some and see

np.zeros(), np.ones(), np.full()

np.arange(), np.linspace()

np.eye()

In [ ]:
arr = np.zeros([5,5])
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
arr = np.ones([5,5])
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
arr = np.full([5,5],6) # full means fill with the any number like here i fill with six
arr

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]])

In [ ]:
arr = np.arange(0,10) # work similar like range function in python
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr = np.linspace(1,5,3) # number being divide in equal space
arr

array([1., 3., 5.])

In [ ]:
arr = np.eye(5) # identity matrix
arr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
arr = np.random.rand(5,5) # random values from 0 to 1 or Normalization
arr

array([[0.24381679, 0.68889579, 0.91934453, 0.02270796, 0.6076481 ],
       [0.25015065, 0.08581709, 0.45124716, 0.77565037, 0.41278134],
       [0.27912289, 0.84051749, 0.27650496, 0.29976305, 0.65730006],
       [0.60413131, 0.29259058, 0.06382858, 0.08829554, 0.47526187],
       [0.64125606, 0.76462068, 0.05170555, 0.87541844, 0.7836966 ]])

In [ ]:
arr = np.random.randint(1,20,10) # random integers in a range
arr

array([ 2, 15, 15, 12,  5, 11, 17, 13,  8,  6])

In [ ]:
arr = np.random.randn(5,5) # random values from bell curve distribution or Standardization
arr

array([[ 1.74462501, -0.23551819, -0.93128077, -1.07275469,  0.91851151],
       [-2.91940166, -0.76402069,  0.97611075, -0.91357354,  0.45516806],
       [ 0.75844751,  0.99520609,  0.0127674 ,  1.9966023 , -0.20291695],
       [-0.76649032,  0.43430406,  0.08333122,  0.63616881, -0.55259038],
       [ 0.17971665, -0.86538168, -1.01584666,  0.82296695, -0.00405217]])

In [ ]:
arr = np.random.randn(10)
arr

array([ 0.204731  ,  0.34406166,  0.36147309,  0.27206918,  0.12611462,
       -1.17114156, -0.94575156, -0.7035032 ,  0.51093627, -0.11029388])

In [ ]:
arr = np.random.randint(1,20,(3,3)) # random integers in a range
arr

array([[15,  9,  5],
       [ 1,  1,  2],
       [16, 13,  2]])

arange → step-based values

linspace → fixed number of values

eye → identity matrix

rand → random floats (0–1)

randint → random integers in a range

randn → random values from bell curve distribution