##1. Attributes of an Array

Introduce attributes that describe the array.

Attributes: .shape, .ndim, .size, .dtype.

In [ ]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])

print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)

(2, 3)
2
6
int64


##Indexing and Slicing
Now we have Indexing and slicing aswell and for that we are going to see 1d and 2d indexing lets start with **1D indexing** and it is similar to list.

In [ ]:
arr = np.array([1,2,3,4,5,6])
print(arr[0])
print(arr[1])

1
2


Now lets see the 2D indexing aswell

In [ ]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr[1]

array([4, 5, 6])

In [ ]:
arr[1,0]

np.int64(4)

Now we can also do the slicing lets see the **slicing in 1D**

In [ ]:
arr = np.array([1,2,3,4,5,6])
arr[0:4]

array([1, 2, 3, 4])

1D slicing was really easy now lets see the **slicing in 2D**

In [ ]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
arr[1:,1:]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[5, 6],
       [8, 9]])

There is one more thing known as **Boolean indexing**

In [ ]:
arr = np.array([3,5,8,10,13])
print(arr>7)
print(arr[arr>7])

[False False  True  True  True]
[ 8 10 13]


In [ ]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr>5)
print(arr[arr>5])

[[False False False]
 [False False  True]
 [ True  True  True]]
[6 7 8 9]


## Reshaping the Array

you can also reshape the Array as you like but be accurate about the dimensions

In [ ]:
arr = np.arange(1,31).reshape(5,6)
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

## Flattening of an array

you can convert the 2D array to 1D using the Flattening Function

In [ ]:
arr.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])