##Fancy Indexing
you can Pick elements from specific positions using a list/array of indices.

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10])

arr[[0,2,4]]

array([1, 3, 5])

You can do this fancy indexing in 2D Matrix aswell

In [ ]:
matrix = np.arange(1,13).reshape(3,4)
print(matrix)
print(matrix[[0,1],[1,2]])
matrix[[0,1,2],[1,2,3]] # first box for row and second box for column

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[2 7]


array([ 2,  7, 12])

##Conditional Selection
Find values based on conditions or replace them.

In [ ]:
arr = np.array([5,7,9,12,15,17])

arr[arr>9]
np.where(arr>9,arr,0) # the valye are greater than 9 preserve them otherwise replace them with 0


array([ 0,  0,  0, 12, 15, 17])

##Sorting & Ordering
np.sort() → returns sorted array

np.argsort() → returns indices of sorted order

In [ ]:
arr = np.array([15,4,78,35,24,17])
np.sort(arr)

array([ 4, 15, 17, 24, 35, 78])

In [ ]:
np.argsort(arr)

array([1, 0, 5, 4, 3, 2])

##Concatenation & Stacking

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])

np.concatenate([a,b])

array([1, 2, 3, 4, 5, 6])

Vertical & Horizontal Stacking

In [ ]:
a = np.array([[1,2,3],[7,8,9]])
b = np.array([[4,5,6],[10,11,12]])
np.vstack([a,b])

array([[ 1,  2,  3],
       [ 7,  8,  9],
       [ 4,  5,  6],
       [10, 11, 12]])

In [ ]:
np.hstack([a,b])

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

Matrix Operation
scalar and vector production

In [ ]:
a = np.array([[1,2],[7,8]])
b = np.array([[4,5],[3,6]]) # matrix multiplication

print(a@b)
print(np.dot(a,b))

[[10 17]
 [52 83]]
[[10 17]
 [52 83]]


In [ ]:
a.T # transpose of matrix

array([[1, 7],
       [2, 8]])