##Numpy array operations

Lets first see how arrays behave like “vectors/matrices” when operations happen element-wise.

In [ ]:
import numpy as np
a = np.array([1, 2, 3, 4])
b = np.array([1, 2, 1, 2])

print(a + b)
print(a - b)
print(a * b)
print(a // b)

[2 4 4 6]
[0 0 2 2]
[1 4 3 8]
[1 1 3 2]


These things are already different from List and if we talk about one more special power it is **Broadcasting**

In [ ]:
a = np.array([1, 2, 3, 4])


print(a * 2)

[2 4 6 8]


Even these things work with different shaped array the calculations will happen on every row. but dimensions must match

In [ ]:
a = np.array([[1, 2, 3, 4],[5,6,7,8]])
print(a*3)

[[ 3  6  9 12]
 [15 18 21 24]]


#Aggregate Functions

These functions are used to calculate the statistics on arrays.

In [ ]:
arr = np.array([1,3,5,7,9,11])

print(np.sum(arr))
print(np.min(arr))
print(np.max(arr))
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
print(np.var(arr))

36
1
11
6.0
6.0
3.415650255319866
11.666666666666666


You can also do the axis based operations row-Wise and Colum-wise